#!/usr/bin/python

"""
FSCAT - Organize media collections in multiple taxonomies using Unix hard links

Copyright (C) 2014  Dario Chiappetta, dario@repni.it

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

import os,sys,re
from glob import glob
from shutil import rmtree
from xml.dom import minidom
import logging

__author__  = "Dario Chiappetta"
__email__   = "dario@repni.it"
__version__ = "0.1"
__status__  = "development"

DIR_DATA    = "_data/"
DIR_IDX     = "./"
CONFFILE    = ".fscat.conf"
METAFILE    = ".meta"			# TODO: change in .fscat.meta

KW_STOP = "S"
KW_SKIP = "K"

UNDEFINED_NAME = "_UNDEFINED_"

LOGGING_LEVEL = logging.DEBUG

#
# COMMANDS
#

def build_indices(root = "./"):
	"""
	Reads the Collection configuration file (.fscat.conf), and crawls the 
	subfolders of the data directory (whose name, '_data/' is currently fixed),
	searching for metafiles. When a metafile is found, the corresponding media
	is added to the indices defined in the Collection.
	
		'root'   Is the absolute or relative path to the directory containing 
		         the collection configuration file (.fscat.conf) and the data
		         folder '_data/'
	"""
	
	logging.debug("Indices build started")
	
	#~ root     = os.path.abspath(root)+"/"
	#~ dataroot = os.path.join(root, DIR_DATA)
	root     = abspath(root)
	dataroot = abspath(DIR_DATA, root)
	
	collection = get_collection_from_XML(root)
	if not collection:
		logging.error("Errors occurred reading collection's configuration file. Aborting.")
		return False

	"""Remove existing indices, if present"""
	for i in collection.indices:
		if os.path.exists(i.root):
			print("Old index found: must be removed to continue.")
			if not yn_remove_folder(i.root):
				return False	
			
	"""Build the updated indices"""
	for d in [x[0] for x in os.walk(dataroot)][1:]:
		metafile_path = abspath(METAFILE, d)
		movies = get_movies_from_XML(metafile_path)
		if movies:
			for m in movies:
				#~ add_to_index_az(d+"/",m)
				#~ add_to_index_gen(d+"/",m)
				for i in collection.indices:
					add_to_index(d,m,i)
			
	return True

def edit_meta(movieroot = "./"):
	"""
	Edit the metadata for the movie in the specified directory. Create metadata
	file if not already present.
	
		'movieroot'   Is the folder, in the data directory, containing the source
		              files of the movie, along with, possibly, the metafile.
					
	TODO: THIS FUNCTION IS OUTDATED!
	"""
	
	logging.debug("Editing metadata for movie in the current folder")

	"""Enforce trailing slash in path"""
	movieroot = os.path.abspath(movieroot)+"/"

	"""If metadata already present, resue information"""
	# TODO: now get_movies_from_XML() returns a list, following code must be 
	#       updated
	m = get_movies_from_XML(movieroot+METAFILE)
	if m:
		p_title = m.title
		p_year  = m.year
		p_genre = m.genre
		p_files = m.files
	else:
		p_title, p_year, p_genre, p_files = guess_meta(movieroot)

	n_title = input("title: ["+p_title+"] ")
	if n_title == "":
		n_title = p_title
	
	n_year  = input("year: ["+p_year+"] ")
	if n_year == "":
		n_year = p_year
		
	n_genre = input("genre: ["+p_genre+"] ")
	if n_genre == "":
		n_genre = p_genre
	
	filelist = []
	stop = False
	for f in p_files:
		filename_in = input("file ("+KW_STOP+" to terminate, "+KW_SKIP+" to skip): ["+f+"] ")
		
		if filename_in == KW_STOP:
			stop = True
			break
		
		if filename_in is not KW_SKIP:
			filelist.append(f)
	
	filename_in = None
	while True:
		if stop or filename_in == KW_STOP:
			break
		
		if filename_in and filename_in is not "":
			filelist.append(filename_in)
		
		filename_in = input("file ("+KW_STOP+" to terminate): ")
	
	n_movie = Movie(n_title, n_year, n_genre, filelist)
		
	print(n_movie.get_xml())
	
	stop = False
	while stop == False:
		write_yn = input("\nCorrect? [Y/n] ")
		
		if (write_yn == "") or (write_yn.lower() == "y"):
			stop = True
			metafile = open(movieroot+METAFILE,"w")
			metafile.write(n_movie.get_xml())
			metafile.close()
			print("Metadata written to "+movieroot+METAFILE)
		elif write_yn.lower() == "n":
			stop = True
			print("Metadata were not updated")
		else:
			print("Invalid input. Please answer with 'y' or 'n'.")
		

def init_meta(dataroot = DIR_DATA):
	"""
	Loops (not recursively) through the subdirectories of 'dataroot', creating
	metadata for each folder (or editing them, if already present)
	
		'dataroot'   Is the data root folder, containing all the media of the 
		             collection.
					
	TODO: THIS FUNCTION IS OUTDATED
	"""
	
	#
	# TODO: update this function and its calls: should receive only absolute
	#       paths
	#
	
	"""Check if data directory exists"""
	if not os.path.exists(dataroot):
		logging.error("Invalid data directory: "+os.path.abspath(dataroot))
		return False
	
	"""Build the updated index"""
	for d in [x[0] for x in os.walk(dataroot)][1:]:
		
		stop = False
		while not stop:
			edit_yn = input("Edit metadata for "+os.path.abspath(d)+"? [y/N] ")
			
			if (edit_yn.lower() == "y"):
				stop = True
				edit_meta(d)
			elif (edit_yn.lower() == "") or (edit_yn.lower() == "n"):
				stop = True
				print("Skipping.")
			else:
				print("Invalid input. Please answer with 'y' or 'n'.")
			
		print()
		
	return True

#
# UTIL_EDIT
# Utility methods for the 'edit' command
#

def guess_meta(movieroot):
	"""
	Guesses the metadata from file and folder names
	
		'movieroot'   Is the folder, in the data directory, containing the source
		              files of the movie, along with, possibly, the metafile.
	"""
	
	"""files: all the possible video and subtitle files"""
	# FIXME: glob looks in current directory, instead of movie root
	files = glob(movieroot + "*.avi") + \
	        glob(movieroot + "*.mkv") + \
	        glob(movieroot + "*.mp4") + \
	        glob(movieroot + "*.srt")
	
	files = [os.path.basename(x) for x in files]
	
	"""title: the folder name"""
	title = movieroot.split("/")[-2]

	"""year: most frequent year match in video files or folder name"""
	year = ""
	candidate_years = []
	for i in files + [title]:
		candidate_years = candidate_years + re.findall(r"[1-2][0-9]{3}", i)
	if len(candidate_years) > 0:
		year = max(set(candidate_years), key=candidate_years.count)
	
	"""genre: not guessed at the moment..."""
	genre = ""
	
	return title, year, genre, files

#
# UTIL_BUILD
# Utility methods for the 'build' command
#

def yn_remove_folder(path):
	"""
	Prompts the user with the question wether the given 'path' should be 
	removed or not. On affirmative answer, removes 'path' and all its content.
	
		'path'   Path to the directory to be removed
	"""
	
	ans = input("Remove '"+path+"' and its content? [y/N] ")
	if (ans.lower() == 'y'):
		rmtree(path)
		return True
	elif (ans.lower() == 'n' or ans == ''):
		return False
	else:
		print("Please answer with 'y' or 'n'.")
		return yn_remove_folder(path)

def add_to_index(src_path, movie, index):
	"""
	Adds the given 'movie' to 'index'.
	
		'src_path'	Is the folder, in the data directory, where the source 
					files of the movie are placed.
		'movie'		Is a Movie object
		'index'		Is a Index object
	"""
	
	"""Extract features from movie"""
	feat = {}
	feat["TITLE"]   = movie.title
	feat["YEAR"]    = movie.year
	feat["GENRE"]   = movie.genre
	feat["INITIAL"] = movie.title[0].upper()
	
	"""Build path by replacing features in the definition"""
	idx_path = index.path
	for k in feat.keys():
		idx_path = idx_path.replace("$"+k,feat[k])
	
	idx_path = os.path.join(index.root, idx_path)
	
	"""Create the index directory, if not already existing"""
	if not os.path.exists(idx_path):
		os.makedirs(idx_path)
		
	"""Create a hardlink to the movie file(s)"""
	for f in movie.files:
		src  = os.path.join(src_path, f)
		dest = os.path.join(idx_path, f)
		try:
			os.link( src, dest )
		except FileNotFoundError:
			logging.warning("File not found: "+src+". Skipped. It is "+\
			                "recommended to update movie entry.")

	logging.debug("Added '"+movie.title+"' to index '"+index.name+"' ("+idx_path+")")


#
# UTIL_MISC
# Utility methods used in various parts of the code
#

def abspath(path, root = "./"):
	"""
	Like 'os.path.abspath()', returns a normalized absolutized version of the 
	pathname 'path'. In addition, a different root can be optionally used in 
	place of the current working directory.
	
		'path'   Is an absolute or relative path, will be normalized, absolutized
                 and returned.
		'root'   Is an absolute or relative path, will be used as root for 'path',
                 if possible.
	"""
	
	root = os.path.abspath(root)
	
	return os.path.normpath( os.path.join(root, path) )
	
#
# FACTORY
#

def get_movies_from_XML(filepath):
	"""
	Returns a list of Movie objects built upon the <movie> entries found in the
	given .meta description file
		
		'filepath'   Is the path to the XML file to be read
	"""
	
	if not os.path.isfile(filepath):
		return False
	
	try:
		meta = minidom.parse(filepath)
	except:
		logging.warning("Invalid content for metafile: "+filepath)
		return False
	
	r = []
	
	"""For every <media> element in the metafile"""
	medias = meta.getElementsByTagName("media")
	for media in medias:
		"""Get the movie files (there can be 1 or more)"""
		files = []
		elements = media.getElementsByTagName("file")
		for tag in elements:
			assert tag.childNodes[0].nodeType == tag.childNodes[0].TEXT_NODE
			files.append(tag.childNodes[0].data)
		
		"""Get the other properties"""
		properties = {}
		for p in Movie.PROPERTIES:
			elements = media.getElementsByTagName(p)
			
			assert len(elements) == 1
			tag = elements[0]
			
			try:
				assert tag.childNodes[0].nodeType == tag.childNodes[0].TEXT_NODE
				properties[p] = tag.childNodes[0].data
			except IndexError:
				logging.warning("Empty value for property '"+p+"' in metafile "+filepath)
				properties[p] = ""
		
		"""Builds and appends a Movie object representing the <media> entry"""
		r.append(Movie(properties["title"],properties["year"],properties["genre"], files))
	
	return r

def get_collection_from_XML(root):
	"""
	Returns a Collection object built from the collection's configuration file,
	.fscat.conf
	
		'root'   Is an absolute path to the directory containing the 
                 configuration file (e.g. '/home/dario/collections')
	"""

	filepath = os.path.join(root, CONFFILE)

	if not os.path.isfile(filepath):
		logging.warning("Impossible to open '"+filepath+"' for reading.")
		return False
	
	try:
		conf = minidom.parse(filepath)
	except:
		logging.warning("Invalid content for configuration file: "+filepath)
		return False
	
	"""Get the main <collection> tag"""
	collection = conf.getElementsByTagName("collection")
	assert len(collection) == 1
	collection = collection[0]
	name_processed = False
	
	"""Process the content of the collection"""
	name    = None
	indices = []
	for node in collection.childNodes:
		if node.localName == "index":
			i = _get_index_from_XML_element(node, root, filepath)
			if i:
				indices.append(i)
			
		elif node.localName == "name":
			if name_processed:
				logging.warning("Duplicate 'name' entry in '"+filepath+"'")
			name = _get_XML_tag_value(node)
			name_processed = True
		
		elif node.localName is not None:
			logging.warning("Unknown tag '"+node.localName+"' in '"+filepath+"'. Skipping.")

	if not name:
		logging.warning("Missing 'name' tag for collection in '"+filepath+"'")
		name = UNDEFINED_NAME
	if len(indices) == 0:
		logging.warning("No index defined in '"+filepath+"'")
		return False
	
	return Collection(name,indices)
	

def _get_index_from_XML_element(element, c_root, source = None):
	"""
	Builds and returns a CollectionIndex object from a <index> element (supposed
	to be found in the collection's .fscat.conf), as it is parsed by minidom.
	
		'element'   Is the Dom Element containing the index
		'c_root'    Is the root directory of the collection
		'source'    Is the path to the source XML file, used for error messages
	"""
	
	name = None
	root = None
	path = None
	
	"""Extract information from XML"""
	name_processed = False
	root_processed = False
	path_processed = False
	for node in element.childNodes:
		if node.localName == "name":
			if name_processed:
				logging.warning("Duplicate entry 'name' in '"+source+"'")
			name = _get_XML_tag_value(node)
			name_processed = True
			
		elif node.localName == "root":
			if root_processed:
				logging.warning("Duplicate entry 'root' in '"+source+"'")
			root = _get_XML_tag_value(node)
			root = abspath(root, c_root)
			root_processed = True
			
		elif node.localName == "path":
			if path_processed:
				logging.warning("Duplicate entry 'path' in '"+source+"'")
			path = _get_XML_tag_value(node)
			if os.path.isabs(path):
				logging.warning("Absolute path given as 'path' in index in '"+\
				                source+"'. This is not supposed to happen and "+\
				                "will produce unexpected results.")
			path_processed = True
			
		elif node.localName is not None:
			logging.warning("Unknown tag '"+node.localName+"' in '"+source+"'. Skipping.")

	
	"""Check for missing parameters"""
	if not name:
		logging.warning("Missing 'name' for index in '"+source+"'.")
		name = UNDEFINED_NAME
	if not root:
		logging.warning("Missing 'root' for index in '"+source+"'.")
		return False
	if not path:
		logging.warning("Missing 'path' for index in '"+source+"'.")
		return False
	
	"""Return the CollectionIndex object"""
	return CollectionIndex(name, root, path)


def _get_XML_tag_value(node, source = None):
	"""
	Returns the string contained in the given DOM Node, or an error if the node
	does not contain a string (e.g. other nodes).
	
		'node'      is the DOM Node
		'source'    Is an identifier of the source (e.g. the XML file), will be
                    displayed in case of error
	"""

	if source is not None:
		source_msg = " in '"+source+"'"
	else:
		source_msg = ""

	if len(node.childNodes) != 1:
		logging.warning("Invalid content for '"+node.localName+"'"+source_msg)
		return False
	
	return node.childNodes[0].nodeValue
	
#
# CLASSES
#

class Movie(object):
	
	PROPERTIES = ["title", "year", "genre"]
	
	def __init__(self, title, year, genre, files):
		self.title = title
		self.year  = year
		self.genre = genre
		self.files = files
		
	def get_xml(self):
		"""
		Returns the movie in the fscat XML format.
		
		TODO: This should be replaced with a template engine
		"""
		
		r = "<media type='movie'>\n"
		
		for f in self.files:
			r += "	<file>"+f+"</file>\n"
		
		r += "	<title>"+self.title+"</title>\n"
		r += "	<year>"+self.year+"</year>\n"
		r += "	<genre>"+self.genre+"</genre>\n"
		
		return r+"</media>"

class Collection(object):
	
	def __init__(self, name, indices):
		self.name    = name
		self.indices = indices
	

class CollectionIndex(object):
	
	def __init__(self, name, root, path):
		self.name = name
		self.root = root
		self.path = path


#
# MAIN
#

if __name__ == '__main__':
	logging.basicConfig(level=LOGGING_LEVEL)
	
	try:
		if (sys.argv[1] == "build"):
			
			try:
				root = sys.argv[2]
			except IndexError:
				root = None
			
			if build_indices(root):
				print("Indices successfully built")
			else:
				print("Errors occurred. No index was built.")
				
		elif (sys.argv[1] == "edit"):
			#~ try:
			edit_meta(sys.argv[2])
			#~ except IndexError:
				#~ print("USAGE: fscat edit PATH")
		
		elif (sys.argv[1] == "init"):
			try:
				d = sys.argv[2]
			except IndexError:
				d = DIR_DATA
			
			if init_meta(d):
				print("Medadata initialized correctly")
			else:
				print("Errors occurred. Metadata initialization not completed.")
		
		elif (sys.argv[1] == "help"):
			print("Fscat "+__version__)
			print("No help screen available... Check the code.")
		
		else:
			print("Invalid parameter: "+sys.argv[1])
	except IndexError:
		print("USAGE: fscat COMMAND [OPTIONS]")
